# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('DO', 'Doing'), ('DN', 'Done')], default='TD', max_length=200),
        ),
    ]
