# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190606_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('SEO', 'SEO'), ('SEM', 'SEM'), ('Social Media', 'Social Media')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=30),
        ),
    ]
