# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190606_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request')], max_length=30, null=True),
        ),
    ]
