# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
